export {default as Home} from './home'
export {default as Contact} from './contact'
export {default as About} from './about'
export {default as Enquiry} from './enquiry'
export {default as Product} from './product'
export {default as Blog} from './blog'
export {default as Certificates} from './certificates'